platform :ios, '13.0'
use_frameworks!
  
target 'FlickrBrowser' do
  pod 'Alamofire',                         '5.1'
  pod 'AlamofireImage',                    '~> 4.1.0'
  pod 'Lightbox',                          '~> 2.4.2'
  pod 'PureLayout',                        '~> 3.1.8'
  pod 'R.swift',                           '~> 5.1.0'
  pod 'NSObject+Rx',                       '5.0.2'
  pod 'RxSwift',                           '5.1.0'
  pod 'RxSwiftExt',                        '5.2.0'
  pod 'SVProgressHUD',                     '~> 2.2.5'
end

post_install do |installer|
  puts 'Removing static analyzer support'
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks"
    end
  end
end
